=== simarjeetsingh/Java/Cotxox_JAXB/src/main/resources/org/foobarspam/cotxox_JAXB/schemas/Cotxox.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="https://api.mobipalma.mobi/docs/"
		xmlns:emt="https://api.mobipalma.mobi/docs/" 
		elementFormDefault="unqualified">
     
    <element name="carrera" type="emt:Carrera"></element> 
     
    <complexType name="Carrera">
    	<sequence>
    		<element name="tarjetaCredito" type="string"></element>
    		<element name="origen" type="string"></element>
    		<element name="destino" type="string"></element>
    		<element name="distancia" type="double"></element>
    		<element name="tiempoEsperadoMinutos" type="int"></element>
    		<element name="tiempoCarrera" type="int"></element>
    		<element name="costeEsperado" type="double"></element>
  			<element name="propina" type="int"></element>
    		<element name="costeTotal" type="double"></element>
       		<element name="conductor" type="emt:Conductor"></element>
    	</sequence>
    </complexType>
       
    <complexType name="Conductor">
    	<sequence>
    		<element name="nombre" type="string"></element>
    		<element name="matricula" type="string"></element>
    		<element name="modelo" type="string"></element>
    		<element name="valoraciones" type="emt:ArrayListValoraciones"></element>
    		<element name="ocupado" type="boolean"></element>
    		<element name="valoracionMedia" type="double"></element>
    	</sequence>
 	</complexType>
 	
 	<simpleType name="ArrayListValoraciones">
	 	   <list itemType="byte"/>
 	</simpleType>
    
</schema>

=== simarjeetsingh/Java/Cotxox_JAXB/src/main/resources/org/foobarspam/cotxox_JAXB/schemas/Cotxox.xml
<?xml version="1.0" encoding="UTF-8"?>
<emt:carrera xmlns:emt="https://api.mobipalma.mobi/docs/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://api.mobipalma.mobi/docs/ Cotxox.xsd ">
  <tarjetaCredito>tarjetaCredito</tarjetaCredito>
  <origen>Palma</origen>
  <destino>Palmanova</destino>
  <distancia>15.0</distancia>
  <tiempoEsperadoMinutos>14</tiempoEsperadoMinutos>
  <tiempoCarrera>15</tiempoCarrera>
  <costeEsperado>14.0</costeEsperado>
  <propina>2</propina>
  <costeTotal>16.0</costeTotal>
  <conductor>
    <nombre>Fox</nombre>
    <matricula>2879FFR</matricula>
    <modelo>Peugeot 308</modelo>
    <valoraciones>4 5 4 5 </valoraciones>
    <ocupado>true</ocupado>
    <valoracionMedia>4.5</valoracionMedia>
  </conductor>
</emt:carrera>
